server:
  port: 8080


zhipu:
  api-key: acff095804514aa996485eb9be76cdd3.OxuBDUhcZ8vynZaL



openai:
  api-key: acff095804514aa996485eb9be76cdd3.OxuBDUhcZ8vynZaL
    
    
    
#logging:
#  level:
#    dev.langchain4j: DEBUG          # 核心！
#    dev.langchain4j.ollama: DEBUG
#    dev.langchain4j.zhipu: DEBUG    # 智谱日志
#    dev.langchain4j.model: DEBUG