spring:
  port: 8080
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

zhipu:
  api-key: dca6077c862f40fc9d289fe39ba51325.UQWWSQ0BFmOGz5uM

openai:
  api-key: acff095804514aa996485eb9be76cdd3.OxuBDUhcZ8vynZaL
    
    
    
logging:
  level:
    dev.langchain4j: DEBUG          # 核心！
    dev.langchain4j.store.embedding: DEBUG
    dev.langchain4j.ollama: DEBUG
    dev.langchain4j.zhipu: DEBUG    # 智谱日志
    dev.langchain4j.model: DEBUG

# 自定义 ES 配置（供我们手动构建 Bean 使用）
elasticsearch:
  host: 192.168.30.129
  port: 9200
  username: elastic
  password: 1+1=2yes
  index-name: rag_knowledge_base         # 向量存储的索引名
