server:
  port: 8080


spring:
  application:
    name: scene
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scene
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hello.entity
  configuration:
    map-underscore-to-camel-case: true


